####################################################################################     
#                      Code to reproduce the simulations for LangevinSSM           #
# for the manuscript "Inferring resource selection and utilization distributions   #
#               irregular and error-prone animal tracking data"                    # 
#                                                                                  #
#                                                                                  #
#                                                                                  #
#          Fanny Dupont, Brett T. McClintock, Jan-Ole Fisher, Nigel E. Hussey,     #
#                         Marianne Marcoux, Marie Auger-Méthé                      #
#                                                                                  #
####################################################################################



library(tidyverse)
library(terra)
library(viridis)
library(ggplot2)
library(Rcpp)
library(aniMotum) # remotes::install_github("ianjonsen/aniMotum")
library(fields)
library(TMB)
library(future)
library(furrr)
library(langevinSSM) # remotes::install_github("bmcclintock/langevinSSM")
source("init.mu_aniMotum.R")
model <- c("underdamped","overdamped")[1]

nsims <- 120 # number of simulations
nbAnimals <- 5 # number of tracks
obsPerAnimal <- 5000 # number of simulated locations per track
timeStep <- 0.01 # time scale of simulation (should be small to help prevent discretization error)

beta <-  c(-4, 6, 5) # resource selection coefficients for the spatial covariates (cov_1, cov_2, ... cov_ncov, d2c)
ncov <- length(beta) # number of spatial covariates to be generated using simCov
sigma <- 5 # diffusion (or speed) parameter
gamma <- 0.5 # friction parameter (smaller value -> more directional persistence); ignored unless model=="underdamped"
psi <- 1 # error ellipse scaling parameter

useInitialValues <- TRUE # logical indicating whether or not to use initial values generated by langevinSSM::initialValues
initialInner <- TRUE # logical indicating whether or not to use an initial inner optimization for the random effects (``mu'' and/or ``vel'') before optimizing over all parameters
map <- list(psi=factor(NA)) # map for fixing parameters

## sampling rate, missing data, and measurement error
samplingRate <- 1 # for subsampling observations from true continuous-time model (e.g. if samplingRate = 2 then data are roughly thinned by 2); must be >= 1; note bias increases with samplingRate, but relationships largely preserved
propMissing <- 0.6 # 0.15 0.20 0.25 0.30 0.40 0.45 0.60 0.70 proportion of missing observations; passed as NA observations to TMB (so corresponding true locations treated as random effects to be estimated)
use_aniMotum <- FALSE # logical indicating whether or not to use aniMotum to impute missing locations; if FALSE, langevinSSM uses linear interpolation

smaj.sd <- 2 # SD for semi-major error ellipse axis; smaj ~ abs(Normal(0,smaj.sd)): 0.05 (1%),0.5 (10%),1 (20%), 1.25 (25%),1.666667 (30%), 2 (40%), 2.5 (50%)
smin.sd <- smaj.sd/2 # SD for semi-minor error ellipse axis; smin ~ abs(Normal(0,smin.sd))
eor <- c(0,180) # range for error ellipse orientation (in degrees from north); eor ~ Uniform(eor[1],eor[2])
measurementError <- list(smaj.sd=smaj.sd,smin.sd=smin.sd,eor=eor) # setting measurementError <- NULL adds no measurement error to observations

## specify scale and spatial autocorrelation for covariates
sca <- 200 # bounding box scale
covRange <- c(0.1,0.5) # lower and upper bounds for covariate spatial range parameter (lower has less spatial autocorrelation)
covTimes <- 1 # number of time-varying covariate layers (if >1, then each covariate is a SpatRaster with covTimes layers; if 1, then each covariate is a single-layer SpatRaster)
ztimes <- seq(0,obsPerAnimal*timeStep,length=covTimes) # z (i.e. time) values for raster stacks

## smooth gradient specifications (based on adjacent cells)
## slows model fitting, but can potentially reduce bias if \Delta_t is large (i.e. samplingRate > 1) relative to timeStep (Blackwell & Matthiopoulos 2024, https://doi.org/10.1002/ecy.4457) or if measurement error is large relative to raster cell resolution
npoints <- 0 # number of smoothing points around current cell (0 = none, 4 = diagonal, 8 = queen neighborhood);
curweight <- 1/2 # smoothing weight of current cell location; ignored if npoints=0
weights <- c(curweight,rep((1-curweight)/npoints,npoints)) # smoothing weights (must be of length 5 or 9 and sum to 1); ignored if npoints=0
zetaScale <- 2 # scale factor for smooth gradient neighborhood (>1 increases, <1 decreases neighborhood); underdamped Langevin neighborhood = zetaScale * sqrt(2*pi) * sigma; overdamped langevin neighborhood = zetaScale * sigma / sqrt(2); ignored if npoints=0

langSim <- subDat  <- list()
langFit <- langFit_true <- vector("list", nsims) 
spatialCovs <- list()
nllk_true <- nllk <- idx <- array()
parMat <- matrix(NA,nrow=nsims,5+ifelse(model=="underdamped",1,0))
if(model=="overdamped"){
  colnames(parMat) <- c(paste0("beta",1:ncov),"sigma","BA")
} else colnames(parMat) <- c(paste0("beta",1:ncov),"sigma","gamma","BA")

dataName <- paste0(model,"_nbAnimals",nbAnimals,"_obsPerAnimal",obsPerAnimal,"_timeStep",timeStep,"","_beta",paste0(beta,collapse = "_"),"_sigma",sigma,"_gamma",gamma,"_psi",psi,"_sca",sca,"_covRange",paste0(covRange,collapse="_"),
                   ifelse(!is.null(measurementError),paste0("_smaj",measurementError$smaj.sd,"_smin",measurementError$smin.sd,"_eor",paste0(measurementError$eor,collapse="_")),""),ifelse(covTimes>1,paste0("_covTimes",covTimes),""))

set.seed(1,kind="Mersenne-Twister",normal.kind = "Inversion")
if(!file.exists(paste0("data/",dataName,".RData"))){
  for(isim in 1:nsims){
    cat("Simulation",isim,"\n")
    #######################
    ## Define covariates ##
    #######################
    # Generate ncov spatial covariates
    message("   Generating covariates...")
    spatialCovs[[isim]] <- list()
    
    for(i in 1:ncov) {
      spatialCovs[[isim]][[i]] <- list()
      if(covTimes>1){
        for(ztime in 1:length(ztimes)){
          irange <- runif(1,covRange[1],covRange[2])
          spatialCovs[[isim]][[i]][[ztime]] <- simCov(sca = sca, irange=irange, sigma2 = 0.1, kappa = 0.5)
          terra::time(spatialCovs[[isim]][[i]][[ztime]]) <- ztimes[ztime]
          # terra::crs(spatialCovs[[isim]][[i]]) <- "epsg:3416"
        }
        spatialCovs[[isim]][[i]] <- spatialCovs[[isim]][[i]]
      } else {
        irange <- runif(1,covRange[1],covRange[2])
        spatialCovs[[isim]][[i]] <-  simCov(sca = sca, irange=irange, sigma2 = 0.1, kappa = 0.5)
        # terra::crs(spatialCovs[[isim]][[i]]) <- "epsg:3416"
      }
    }
    
    names(spatialCovs[[isim]]) <- c("cov1","cov2","cov3")
    if(model=="underdamped"){
      par <- list(beta=beta,sigma=sigma,gamma=gamma,psi=psi)
    } else {
      par <- list(beta=beta,sigma=sigma,psi=psi)
    }
    
    # simulate "high resolution" tracks; this can take a while...
    langSim[[isim]] <- tryCatch(stop(),error=function(e) e)
    attempts <- 0
    while(inherits(langSim[[isim]],"error") && attempts < 200){
      attempts <- attempts + 1
      langSim[[isim]] <- tryCatch(simLangevin(
        model = model,
        nbAnimals = nbAnimals,
        obsPerAnimal = obsPerAnimal,
        timeStep = timeStep,
        par=par,
        spatialCovs = spatialCovs[[isim]],
        measurementError = measurementError
      ),error=function(e) e)
      if(inherits(langSim[[isim]],"error")){
        message("    Retrying Simulation ",isim," (attempt ",attempts,"): ",langSim[[isim]]$message)
      }
    }
    if(inherits(langSim[[isim]],"error")){
      message("    Skipping Simulation ",isim," after 200 failed attempts.")
      next
    }
  }
  # Inside your simulation loop, right before save()
  if(!dir.exists("data")) dir.create("data")
  
  # Wrap the SpatRasters for safe saving
  spatialCovs_wrapped <- list()
  for(isim in 1:length(spatialCovs)) {
    spatialCovs_wrapped[[isim]] <- list()
    for(i in 1:length(spatialCovs[[isim]])) {
      spatialCovs_wrapped[[isim]][[i]] <- terra::wrap(spatialCovs[[isim]][[i]])
    }
    names(spatialCovs_wrapped[[isim]]) <- names(spatialCovs[[isim]])
  }
  # Save the wrapped version
  save(langSim, spatialCovs_wrapped, file=paste0("data/", dataName, ".RData"))
} else {
  load(paste0("data/",dataName,".RData"))
  
  # Unwrap the saved rasters back into SpatRaster objects
  spatialCovs <- list()
  for(isim in 1:length(spatialCovs_wrapped)) {
    spatialCovs[[isim]] <- list()
    for(i in 1:length(spatialCovs_wrapped[[isim]])) {
      spatialCovs[[isim]][[i]] <- terra::unwrap(spatialCovs_wrapped[[isim]][[i]])
    }
    names(spatialCovs[[isim]]) <- names(spatialCovs_wrapped[[isim]])
  }
}
# subsample data
set.seed(1, kind="Mersenne-Twister", normal.kind = "Inversion")
for(isim in 1:nsims){
  if(is.null(langSim[[isim]]) || inherits(langSim[[isim]], "error")){
    next
  }
  subDat[[isim]] <- subSampleData(langSim[[isim]], samplingRate = samplingRate, propMissing = propMissing)
}

for(isim in 1:nsims){
  cat("Simulation",isim,"\n")
  # Compute utilization distribution
  UD <- getUD(spatialCovs[[isim]], beta=beta,log=TRUE)
  
  # Plot covariates
  ggtheme <- theme(axis.title = element_text(size=12), axis.text = element_text(size=12),
                   legend.title = element_text(size=12), legend.text = element_text(size=12))
  c1plot <- plotRaster(spatialCovs[[isim]][[1]], legend.title = expression(c[1])) + ggtheme
  c2plot <- plotRaster(spatialCovs[[isim]][[2]], legend.title = expression(c[2])) + ggtheme
  c3plot <- plotRaster(spatialCovs[[isim]][[3]], legend.title = expression(c[3])) + ggtheme
  UDplot <- plotRaster(UD, legend.title = expression(pi)) + ggtheme
  
  # generate missing data using aniMotum
  if(propMissing>0 && any(is.na(subDat[[isim]]$x))){
    if(use_aniMotum){
      message("   Fitting aniMotum separately to each track...")
      notNA <- which(!is.na(subDat[[isim]]$x))
      future::plan(future::multisession,workers=min(nbAnimals,parallel::detectCores()-1))  # workers sets number of cores to use
      init.mu <- init.mu_aniMotum(subDat[[isim]][notNA,],model="rw",timeSteps=data.frame(id=as.character(subDat[[isim]]$id),date=as.POSIXlt(subDat[[isim]]$date * 1000))) # fit_ssm doesn't like very small \Delta_t
      #init.mu <- subDat[[isim]][,c("mu.x","mu.y")] # true values
      par$mu=init.mu
      
      if(model=="underdamped"){
        init.vel <- matrix(0,nrow(subDat[[isim]]),2)
        #init.vel <- subDat[[isim]][,c("vel.x","vel.y")] # true values
        par$vel = init.vel
      }
    }
  }
  
  # Fit with the fixed parameters initialized at their true values
  error <- FALSE
  langFit_true[[isim]] <- tryCatch(
    {
      fitLangevin(subDat[[isim]], model = model, par = par, spatialCovs = spatialCovs[[isim]],
                  map = map,
                  smoothGradient = ifelse(npoints > 0, TRUE, FALSE), npoints = npoints, curweight = curweight, zetaScale = zetaScale,
                  silent = TRUE, control = list(trace = 0), initialInner = initialInner)
    },
    error = function(e) {
      message(sprintf("Error in fitLangevin for isim = %d: %s", isim, conditionMessage(e))) # potentially data is outside, triggers an error that Brett checks.
      error <<-TRUE
      NA
    }
  )
  
  if(error){next}
  
  nllk_true[isim] <-   langFit_true[[isim]]$objective
  if(useInitialValues) par <- initialValues(subDat[[isim]],model,par=list(psi=psi),spatialCovs=spatialCovs[[isim]])
  
  # Fit with the fixed parameters initialized at 0
  langFit[[isim]] <- fitLangevin(subDat[[isim]],model=model,par=par,spatialCovs=spatialCovs[[isim]],
                                 map=map,
                                 smoothGradient = ifelse(npoints>0,TRUE,FALSE), npoints = npoints, curweight = curweight, zetaScale = zetaScale,
                                 silent=TRUE, control=list(trace=0),initialInner=initialInner)
  
  nllk[isim] <-   langFit[[isim]]$objective
  
  idx[isim] <- which.min(c(nllk_true[isim],nllk[isim]))
  if( idx[isim]==2){Fit <- langFit}else{Fit <- langFit_true}
  parMat[isim,1:(4+ifelse(model=="underdamped",1,0))] <- Fit[[isim]]$par
  parMat[isim,"sigma"] <- Fit[[isim]]$estimates$natural["sigma",1]
  if(model=="underdamped") parMat[isim,"gamma"] <- Fit[[isim]]$estimates$natural["gamma",1]
  
  zoom_ext <- terra::ext(-100, 100, -100, 100)
  
  par(mfrow=c(2,2))
  plot(UD[[1]], main = paste0("Simulation ", isim), col = viridis::viridis(100))
  points(subDat[[isim]]$x, subDat[[isim]]$y, col = 2) # observed locations
  for(i in 1:nbAnimals) {
    lines(langSim[[isim]]$mu.x[langSim[[isim]]$id==i], langSim[[isim]]$mu.y[langSim[[isim]]$id==i]) # true path
  }
  plot(subDat[[isim]]$x,subDat[[isim]]$y,col=2,asp=1) # observed locations
  for(i in 1:nbAnimals){
    lines(Fit[[isim]]$report$mu[1,subDat[[isim]]$id==i],Fit[[isim]]$report$mu[2,subDat[[isim]]$id==i],type="o",pch=20,col=3) # estimated path
  }
  for(i in 1:nbAnimals){
    lines(langSim[[isim]]$mu.x[langSim[[isim]]$id==i],langSim[[isim]]$mu.y[langSim[[isim]]$id==i]) # true path
  }
  # plot(terra::crop(UD,zoom_ext),main="True UD",col=viridis::viridis(100))
  estUD <- getUD(spatialCovs[[isim]],Fit[[isim]],log=TRUE)
  # plot(terra::crop(estUD,zoom_ext),main="Estimated UD",col=viridis::viridis(100))
  
  parMat[isim,"BA"] <- rasterOverlap(exp(estUD),exp(UD)) # Calculate Bhattacharyya's Affinity between estimated and true UDs
  
  print(paste0("            ",paste0(colnames(parMat),collapse="    ")))
  print(paste0("current ",paste0(round(parMat[isim,],6),collapse=" ")))
  print(paste0("overall ",paste0(round(apply(parMat[1:isim,,drop=FALSE],2,function(x)mean(x,na.rm=TRUE)),6),collapse=" ")))
  
}

if(!dir.exists("results")) dir.create("results")
prop_truebetter <-   mean(idx == 1) 

save(parMat,beta,sigma,gamma,obsPerAnimal,subDat,langFit,langFit_true,prop_truebetter,psi,timeStep,samplingRate,propMissing,measurementError,sca,npoints,curweight,covRange,map,useInitialValues,covTimes,file=paste0("results/",dataName,"_samplingRate",samplingRate,"_propMissing",propMissing,"_aniMotum",use_aniMotum,"_npoints",npoints,"_curweight",curweight,"_zetaScale",zetaScale,".RData"))
